// Generated by CoffeeScript 1.8.0
(function() {
  var Server, Session, app, bodyParser, express, io, router, server, session;

  express = require("express");

  bodyParser = require("body-parser");

  Session = require("express-session");

  Server = require("http").Server;

  router = require("./routes");

  app = express();

  server = Server(app);

  io = require("socket.io")(server);

  session = Session({
    secret: "lkjmagsmohiuy324fm0p8yuagdshklmc190m82y3cr"
  });

  app.use(bodyParser.json());

  app.use(session);

  app.set('views', './views');

  app.set('view engine', 'jade');

  app.use(express["static"]("public"));

  io.use(function(socket, next) {
    return session(socket.request, socket.request.res, next);
  });

  router(app, io);

  server.listen(3000);

}).call(this);
