// Generated by CoffeeScript 1.9.2
(function() {
  var accountController, gameController, roomController;

  accountController = require("./controllers/AccountController");

  roomController = require("./controllers/RoomController");

  gameController = require("./controllers/GameController");

  module.exports = function(app, io) {
    app.post("/account", accountController.create);
    app.get("/account/:username", accountController.read);
    app.post("/account/login", accountController.login);
    app.get("/login", function(req, res) {
      return res.render("login");
    });
    app.get("/register", function(req, res) {
      return res.render("register");
    });
    app.get("/logout", function(req, res) {
      req.session.playerId = null;
      return res.send("Good job");
    });
    app.get("/room/create", roomController.create);
    app.get("/room/:id", roomController.read);
    gameController(io);
    return app.get("/", function(req, res) {
      return res.render("index");
    });
  };

}).call(this);
