// Generated by CoffeeScript 1.8.0
(function() {
  var accountController, roomController;

  accountController = require("./controllers/AccountController");

  roomController = require("./controllers/RoomController");

  module.exports = function(app) {
    app.post("/account/create", accountController.create);
    app.get("/account/:username", accountController.read);
    app.get("/room/create", roomController.create);
    app.get("/room/:id", roomController.read);
    return app.get("/", function(req, res) {
      return res.render("index");
    });
  };

}).call(this);
