// Generated by CoffeeScript 1.10.0
(function() {
  var Account, Room;

  Room = require("../models/Models").room;

  Account = require("../models/Models").account;

  module.exports = function(io) {
    return io.on("connection", function(socket) {
      var _playerId, _roomId;
      _playerId = null;
      _roomId = null;
      socket.on("join", function(data) {
        if (socket.request.session.playerId != null) {
          _playerId = socket.request.session.playerId;
        }
        if (data.roomId != null) {
          _roomId = data.roomId;
          socket.join(_roomId);
        } else {
          return socket.emit("error", {
            error: "Room ID was not included in the join request."
          });
        }
        return Account.findOne({
          _id: _playerId
        }).exec(function(err, account) {
          if ((err == null) && (account != null)) {
            return Room.findOne({
              _id: _roomId
            }).exec(function(err, room) {
              var definition, i, j, len, len1, player, ref, ref1;
              socket.emit("word", {
                word: room.word
              });
              ref = room.definitions;
              for (i = 0, len = ref.length; i < len; i++) {
                definition = ref[i];
                socket.emit("definition", definition);
              }
              ref1 = room.players;
              for (j = 0, len1 = ref1.length; j < len1; j++) {
                player = ref1[j];
                socket.emit("connect", {
                  username: player.username
                });
              }
              return io.to(_roomId).emit("connect", {
                username: account.username
              });
            });
          } else {
            return socket.emit("message", {
              error: "Couldn't find the account '" + _playerId + "'"
            });
          }
        });
      });
      socket.on("definition", function(data) {
        if ((_playerId != null) && (_roomId != null)) {
          return Room.findOne({
            _id: _roomId
          }).exec(function(err, room) {
            var definition, numConnectedClients;
            if (err || (room == null)) {

            } else {
              definition = {
                definition: data.definition,
                playerId: _playerId
              };
              room.definitions.push(definition);
              room.save();
              io.to(_roomId).emit("definition", definition);
              numConnectedClients = Object.keys(io.nsps["/"].adapter.rooms[_roomId]).length;
              if (room.definitions.length >= numConnectedClients) {
                return io.to(_roomId).emit("done", {
                  message: "All definitions have been submitted"
                });
              }
            }
          });
        }
      });
      socket.on("disconnect", function(data) {
        if ((_playerId != null) && (_roomId != null)) {
          return Room.findOne({
            _id: _roomId
          }).exec(function(err, room) {
            if (err || (room == null)) {

            } else {
              return io.to(_roomId).emit("playerDisconnect", _playerId);
            }
          });
        }
      });
      return socket.on("vote", function(data) {
        return Account.findOne({
          _id: _playerId
        }).exec(function(err, account) {
          if ((err == null) && (account != null)) {
            return Room.findOne({
              _id: _roomId
            }).exec(function(err, room) {
              var def, i, len, ref;
              ref = room.definitions;
              for (i = 0, len = ref.length; i < len; i++) {
                def = ref[i];
                if (def.votes.includes(_playerId)) {
                  return;
                } else if (def.playerId === data) {
                  room.definitions.votes.push(_playerId);
                  console.log(room.definitions.votes);
                  room.save();
                }
              }
            });
          }
        });
      });
    });
  };

}).call(this);
