// Generated by CoffeeScript 1.8.0
(function() {
  var Account, Room;

  Room = require("../models/Models").room;

  Account = require("../models/Models").accoun;

  module.exports = function(io) {
    return io.on("connection", function(socket) {
      _playerId;
      _roomId;
      return socket.on("join", function(data) {
        var _playerId, _roomId;
        if (data.roomId != null) {
          _playerId = data.playerId;
          _roomId = data.roomId;
          return socket.join(roomId);
        }
      });
    });
  };

}).call(this);
