// Generated by CoffeeScript 1.9.2
(function() {
  var Account, Room;

  Room = require("../models/Models").room;

  Account = require("../models/Models").account;

  module.exports = function(io) {
    return io.on("connection", function(socket) {
      var _playerId, _roomId;
      _playerId = null;
      _roomId = null;
      socket.on("join", function(data) {
        if (socket.request.session.playerId != null) {
          _playerId = socket.request.session.playerId;
        }
        if (data.roomId != null) {
          _roomId = data.roomId;
          socket.join(_roomId);
        } else {
          return socket.emit("error", {
            error: "Room ID was not included in the join request."
          });
        }
        return Account.findOne({
          _id: _playerId
        }).exec(function(err, account) {
          if ((err == null) && (account != null)) {
            return Room.findOne({
              _id: _roomId
            }).exec(function(err, room) {
              var definition, j, k, l, len, len1, len2, player, ref, ref1, ref2, results;
              room.players.push(account);
              room.save();
              socket.emit("word", {
                word: room.word
              });
              ref = room.definitions;
              for (j = 0, len = ref.length; j < len; j++) {
                definition = ref[j];
                socket.emit("definition", definition);
              }
              ref1 = room.players;
              for (k = 0, len1 = ref1.length; k < len1; k++) {
                player = ref1[k];
                socket.emit("playerJoin", {
                  username: player.username
                });
              }
              io.to(_roomId).emit("connect", {
                username: account.username
              });
              ref2 = room.definitions;
              results = [];
              for (l = 0, len2 = ref2.length; l < len2; l++) {
                definition = ref2[l];
                if (_playerId === definition.playerId) {
                  results.push(socket.emit("hideInput"));
                } else {
                  results.push(void 0);
                }
              }
              return results;
            });
          } else {
            return socket.emit("message", {
              error: "Couldn't find the account '" + _playerId + "'"
            });
          }
        });
      });
      socket.on("definition", function(data) {
        if ((_playerId != null) && (_roomId != null)) {
          return Room.findOne({
            _id: _roomId
          }).exec(function(err, room) {
            var definition, numConnectedClients;
            if (err || (room == null)) {

            } else {
              definition = {
                definition: data.definition,
                playerId: _playerId
              };
              room.definitions.push(definition);
              room.save();
              io.to(_roomId).emit("definition", definition);
              numConnectedClients = Object.keys(io.nsps["/"].adapter.rooms[_roomId]).length;
              if (room.definitions.length >= numConnectedClients) {
                return io.to(_roomId).emit("done", {
                  message: "All definitions have been submitted"
                });
              }
            }
          });
        }
      });
      return socket.on("disconnect", function() {
        console.log(_roomId);
        console.log("disconnect");
        return Room.findOne({
          _id: _roomId
        }).exec(function(err, room) {
          if ((err == null) && (typeof player !== "undefined" && player !== null)) {
            return room.definitions.forEach(function(player, i) {
              return console.log("found one");
            });
          }
        });
      });
    });
  };

}).call(this);
